# Generated by Django 4.2 on 2023-04-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='no_of_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='no_of_days_allowed',
            field=models.IntegerField(),
        ),
    ]
